# SUMMARY FUNCTIONS AND MAPS

SUMMARY FUNCTIONS

In [1]:
import pandas as pd

data = {
    "city": ["Edinburgh", "Valencia", "Madrid", "London", "Paris", "Berlin", "Lisbon", "Rome"],
    "country": ["UK", "Spain", "Spain", "UK", "France", "Germany", "Portugal", "Italy"],
    "temperature_c": [12, 24, 20, 15, 18, 16, 22, 21],
    "population_millions": [0.5, 0.8, 6.7, 9.0, 2.1, 3.7, 0.5, 2.8],
    "is_coastal": [False, True, False, False, False, False, True, False]
}

df = pd.DataFrame(data)
df

        city   country  temperature_c  population_millions  is_coastal
0  Edinburgh        UK             12                  0.5       False
1   Valencia     Spain             24                  0.8        True
2     Madrid     Spain             20                  6.7       False
3     London        UK             15                  9.0       False
4      Paris    France             18                  2.1       False
5     Berlin   Germany             16                  3.7       False
6     Lisbon  Portugal             22                  0.5        True
7       Rome     Italy             21                  2.8       False

In [4]:
#high level summary of the attributes in the given column
df.population_millions.describe()

count    8.000000
mean     3.262500
std      3.112618
min      0.500000
25%      0.725000
50%      2.450000
75%      4.450000
max      9.000000
Name: population_millions, dtype: float64

In [5]:
#mean 
df.temperature_c.mean()

18.5

In [6]:
#list of unique values
df.country.unique()

<ArrowStringArray>
['UK', 'Spain', 'France', 'Germany', 'Portugal', 'Italy']
Length: 6, dtype: str

In [10]:
#list of unique values and how often they occur in the dataset
df.country.value_counts()

country
UK          2
Spain       2
France      1
Germany     1
Portugal    1
Italy       1
Name: count, dtype: int64

MAPS

A function that takes one set of values and "maps" them to another set of values.
Two methods:

1. map()
The function you pass to map() should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

2. apply()
Equivalent method if we want to transform a whole DataFrame by calling a costum method on each row.

In [11]:
#remean the temperatures to 0

df_temp_mean = df.temperature_c.mean()
df.temperature_c.map(lambda p: p - df_temp_mean)

0   -6.5
1    5.5
2    1.5
3   -3.5
4   -0.5
5   -2.5
6    3.5
7    2.5
Name: temperature_c, dtype: float64

In [ ]:
#if there was a description column, count how many times the words "urban" and "traffic" appeared
n_urban = df.description.map(lambda desc: "urban" in desc).sum()
n_traffic = df.description.map(lambda desc: "traffic" in desc).sum()
count = pd.Series([n_urban, n_traffic], index=['urban', 'traffic'])

In [ ]:
#tranform DataFrame by calling a costum method on each row.
def remean_temp(row):
    row.temperature_c = row.temperature_c - df_temp_mean
    return row

df.apply(remean_temp, axis='columns')

        city   country  temperature_c  population_millions  is_coastal
0  Edinburgh        UK           -6.5                  0.5       False
1   Valencia     Spain            5.5                  0.8        True
2     Madrid     Spain            1.5                  6.7       False
3     London        UK           -3.5                  9.0       False
4      Paris    France           -0.5                  2.1       False
5     Berlin   Germany           -2.5                  3.7       False
6     Lisbon  Portugal            3.5                  0.5        True
7       Rome     Italy            2.5                  2.8       False

map() and apply() return new, transformed Series and DataFrames, repectively. They don't modify the original data they are called on.

# GROUPING

In [32]:
#new DataFrame
import pandas as pd

reviews = pd.DataFrame({
    "country": [
        "Spain", "Spain", "Spain",
        "France", "France", "France",
        "Italy", "Italy", "Italy",
        "Portugal", "Portugal",
        "USA", "USA", "USA", "USA"
    ],
    "variety": [
        "Tempranillo", "Garnacha", "Albariño",
        "Merlot", "Chardonnay", "Pinot Noir",
        "Sangiovese", "Nebbiolo", "Pinot Grigio",
        "Touriga Nacional", "Alvarinho",
        "Cabernet Sauvignon", "Zinfandel", "Chardonnay", "Merlot"
    ],
    "winery": [
        "Bodega Sol", "Rioja Estate", "Atlantic Wines",
        "Chateau Vert", "Maison Bleu", "Burgundy Hills",
        "Villa Rosa", "Piedmont Estate", "Veneto Wines",
        "Douro Hills", "Vinho Verde",
        "Golden Vine", "Napa Estate", "Pacific Cellars", "Sonoma Wines"
    ],
    "year": [
        2020, 2020, 2021,
        2019, 2020, 2020,
        2018, 2019, 2021,
        2020, 2021,
        2019, 2020, 2020, 2021
    ],
    "points": [
        92, 89, 91,
        90, 94, 93,
        88, 95, 87,
        91, 89,
        96, 90, 94, 92
    ],
    "price": [
        30, 30, 25,
        40, 35, 35,
        20, 50, 20,
        25, 25,
        60, 30, 30, 45
    ]
})
reviews

     country             variety           winery  year  points  price
0      Spain         Tempranillo       Bodega Sol  2020      92     30
1      Spain            Garnacha     Rioja Estate  2020      89     30
2      Spain            Albariño   Atlantic Wines  2021      91     25
3     France              Merlot     Chateau Vert  2019      90     40
4     France          Chardonnay      Maison Bleu  2020      94     35
5     France          Pinot Noir   Burgundy Hills  2020      93     35
6      Italy          Sangiovese       Villa Rosa  2018      88     20
7      Italy            Nebbiolo  Piedmont Estate  2019      95     50
8      Italy        Pinot Grigio     Veneto Wines  2021      87     20
9   Portugal    Touriga Nacional      Douro Hills  2020      91     25
10  Portugal           Alvarinho      Vinho Verde  2021      89     25
11       USA  Cabernet Sauvignon      Golden Vine  2019      96     60
12       USA           Zinfandel      Napa Estate  2020      90     30
13       USA          Chardonnay  Pacific Cellars  2020      94     30
14       USA              Merlot     Sonoma Wines  2021      92     45

In [33]:
#same as value_counts()
reviews.groupby('points').points.count()

points
87    1
88    1
89    2
90    2
91    2
92    2
93    1
94    2
95    1
96    1
Name: points, dtype: int64

In [34]:
#cheapest in each point value
reviews.groupby('points').price.min()

points
87    20
88    20
89    25
90    30
91    25
92    30
93    35
94    30
95    50
96    60
Name: price, dtype: int64

In [35]:
#name of the first variety of wine reviewed from each year in the dataset
reviews.groupby('year').apply(lambda df: df.variety.iloc[0])

year
2018     Sangiovese
2019         Merlot
2020    Tempranillo
2021       Albariño
dtype: str

In [36]:
#best wine by country and price
reviews.groupby(['country', 'price']).apply(lambda df: df.loc[df.points.idxmax()])

                           variety           winery  year  points
country  price
France   35             Chardonnay      Maison Bleu  2020      94
         40                 Merlot     Chateau Vert  2019      90
Italy    20             Sangiovese       Villa Rosa  2018      88
         50               Nebbiolo  Piedmont Estate  2019      95
Portugal 25       Touriga Nacional      Douro Hills  2020      91
Spain    25               Albariño   Atlantic Wines  2021      91
         30            Tempranillo       Bodega Sol  2020      92
USA      30             Chardonnay  Pacific Cellars  2020      94
         45                 Merlot     Sonoma Wines  2021      92
         60     Cabernet Sauvignon      Golden Vine  2019      96

In [37]:
#agg() lets you run a bunch of different functions on your DataFrame simultaneously
reviews.groupby(['country']).price.agg([len, min, max])

          len  min  max
country
France      3   35   40
Italy       3   20   50
Portugal    2   25   25
Spain       3   25   30
USA         4   30   60

# MULTI-INDEXES

In [38]:
countries_reviewed = reviews.groupby(['country', 'year']).winery.agg([len])
countries_reviewed

               len
country  year
France   2019    1
         2020    2
Italy    2018    1
         2019    1
         2021    1
Portugal 2020    1
         2021    1
Spain    2020    2
         2021    1
USA      2019    1
         2020    2
         2021    1

In [39]:
mi = countries_reviewed.index
type(mi)

pandas.MultiIndex

In [40]:
#convert multi-index back to regular index
countries_reviewed.reset_index()

     country  year  len
0     France  2019    1
1     France  2020    2
2      Italy  2018    1
3      Italy  2019    1
4      Italy  2021    1
5   Portugal  2020    1
6   Portugal  2021    1
7      Spain  2020    2
8      Spain  2021    1
9        USA  2019    1
10       USA  2020    2
11       USA  2021    1

# SORTING

sort_values() defaults to an ascending sort.

In [41]:
countries_reviewed.sort_values(by='len')

               len
country  year
France   2019    1
Italy    2018    1
         2019    1
         2021    1
Portugal 2020    1
         2021    1
Spain    2021    1
USA      2019    1
         2021    1
France   2020    2
Spain    2020    2
USA      2020    2

In [42]:
#descending order

countries_reviewed.sort_values(by='len', ascending=False)

               len
country  year
France   2020    2
Spain    2020    2
USA      2020    2
France   2019    1
Italy    2018    1
         2019    1
         2021    1
Portugal 2020    1
         2021    1
Spain    2021    1
USA      2019    1
         2021    1

In [43]:
#sort by index values

countries_reviewed.sort_index()

               len
country  year
France   2019    1
         2020    2
Italy    2018    1
         2019    1
         2021    1
Portugal 2020    1
         2021    1
Spain    2020    2
         2021    1
USA      2019    1
         2020    2
         2021    1

In [45]:
#sort by more than one column at a time

countries_reviewed.sort_values(by=['country', 'len'])

               len
country  year
France   2019    1
         2020    2
Italy    2018    1
         2019    1
         2021    1
Portugal 2020    1
         2021    1
Spain    2021    1
         2020    2
USA      2019    1
         2021    1
         2020    2

.size()  #count number of rows in every group