# SUMMARY FUNCTIONS AND MAPS

SUMMARY FUNCTIONS

In [1]:
import pandas as pd

data = {
    "city": ["Edinburgh", "Valencia", "Madrid", "London", "Paris", "Berlin", "Lisbon", "Rome"],
    "country": ["UK", "Spain", "Spain", "UK", "France", "Germany", "Portugal", "Italy"],
    "temperature_c": [12, 24, 20, 15, 18, 16, 22, 21],
    "population_millions": [0.5, 0.8, 6.7, 9.0, 2.1, 3.7, 0.5, 2.8],
    "is_coastal": [False, True, False, False, False, False, True, False]
}

df = pd.DataFrame(data)
df

        city   country  temperature_c  population_millions  is_coastal
0  Edinburgh        UK             12                  0.5       False
1   Valencia     Spain             24                  0.8        True
2     Madrid     Spain             20                  6.7       False
3     London        UK             15                  9.0       False
4      Paris    France             18                  2.1       False
5     Berlin   Germany             16                  3.7       False
6     Lisbon  Portugal             22                  0.5        True
7       Rome     Italy             21                  2.8       False

In [4]:
#high level summary of the attributes in the given column
df.population_millions.describe()

count    8.000000
mean     3.262500
std      3.112618
min      0.500000
25%      0.725000
50%      2.450000
75%      4.450000
max      9.000000
Name: population_millions, dtype: float64

In [5]:
#mean 
df.temperature_c.mean()

18.5

In [6]:
#list of unique values
df.country.unique()

<ArrowStringArray>
['UK', 'Spain', 'France', 'Germany', 'Portugal', 'Italy']
Length: 6, dtype: str

In [10]:
#list of unique values and how often they occur in the dataset
df.country.value_counts()

country
UK          2
Spain       2
France      1
Germany     1
Portugal    1
Italy       1
Name: count, dtype: int64

MAPS

A function that takes one set of values and "maps" them to another set of values.
Two methods:

1. map()
The function you pass to map() should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

2. apply()
Equivalent method if we want to transform a whole DataFrame by calling a costum method on each row.

In [11]:
#remean the temperatures to 0

df_temp_mean = df.temperature_c.mean()
df.temperature_c.map(lambda p: p - df_temp_mean)

0   -6.5
1    5.5
2    1.5
3   -3.5
4   -0.5
5   -2.5
6    3.5
7    2.5
Name: temperature_c, dtype: float64

In [ ]:
#if there was a description column, count how many times the words "urban" and "traffic" appeared
n_urban = df.description.map(lambda desc: "urban" in desc).sum()
n_traffic = df.description.map(lambda desc: "traffic" in desc).sum()
count = pd.Series([n_urban, n_traffic], index=['urban', 'traffic'])

In [ ]:
#tranform DataFrame by calling a costum method on each row.
def remean_temp(row):
    row.temperature_c = row.temperature_c - df_temp_mean
    return row

df.apply(remean_temp, axis='columns')

        city   country  temperature_c  population_millions  is_coastal
0  Edinburgh        UK           -6.5                  0.5       False
1   Valencia     Spain            5.5                  0.8        True
2     Madrid     Spain            1.5                  6.7       False
3     London        UK           -3.5                  9.0       False
4      Paris    France           -0.5                  2.1       False
5     Berlin   Germany           -2.5                  3.7       False
6     Lisbon  Portugal            3.5                  0.5        True
7       Rome     Italy            2.5                  2.8       False

map() and apply() return new, transformed Series and DataFrames, repectively. They don't modify the original data they are called on.