# DTYPES

In [13]:
import pandas as pd

df = pd.DataFrame({
    "country": ["Spain", None, "France", "France", "Italy"],
    "variety": [
        "Tempranillo",
        "Garnacha",
        "Merlot",
        "Chardonnay",
        "Sangiovese"
    ],
    "points": [92, 89, 94, 91, 93],
    "price": [30, 25, 35, 40, 28]
})

df

  country      variety  points  price
0   Spain  Tempranillo      92     30
1     NaN     Garnacha      89     25
2  France       Merlot      94     35
3  France   Chardonnay      91     40
4   Italy   Sangiovese      93     28

In [ ]:
df.price.dtype

#int64 means a 64-bit integer number

dtype('int64')

In [6]:
df.dtypes

country      str
variety      str
points     int64
price      int64
dtype: object

In [ ]:
#trasform points column from existing int64 into float64
df.points.astype('float64')

0    92.0
1    89.0
2    94.0
3    91.0
4    93.0
Name: points, dtype: float64

In [8]:
#dataframe or series index has its own dtype too
df.index.dtype

dtype('int64')

# MISSING DATA

Entries missing values are given the value NaN ("Not a number"). For technical issues, these NaN values are always of the float64 dtype.

- pd.isnull()
- pd.notnull()

In [14]:
df[pd.isnull(df.country)]

  country   variety  points  price
1     NaN  Garnacha      89     25

In [15]:
#for replacing missing values
df.country.fillna("Unknown")

0      Spain
1    Unknown
2     France
3     France
4      Italy
Name: country, dtype: str

In [16]:
#update a value
df.price.replace(30, 32)

0    32
1    25
2    35
3    40
4    28
Name: price, dtype: int64