# RENAMING

- rename() lets you change index names and/or column names

In [1]:
import pandas as pd

df = pd.DataFrame({
    "country": ["Spain", None, "France", "France", "Italy"],
    "variety": [
        "Tempranillo",
        "Garnacha",
        "Merlot",
        "Chardonnay",
        "Sangiovese"
    ],
    "points": [92, 89, 94, 91, 93],
    "price": [30, 25, 35, 40, 28]
})

df

  country      variety  points  price
0   Spain  Tempranillo      92     30
1     NaN     Garnacha      89     25
2  France       Merlot      94     35
3  France   Chardonnay      91     40
4   Italy   Sangiovese      93     28

In [ ]:
#rename column
df.rename(columns={'points': 'score'})

  country      variety  score  price
0   Spain  Tempranillo     92     30
1     NaN     Garnacha     89     25
2  France       Merlot     94     35
3  France   Chardonnay     91     40
4   Italy   Sangiovese     93     28

In [3]:
#rename indexes
df.rename(index={0: 'firstEntry', 1: 'secondEntry'})

            country      variety  points  price
firstEntry    Spain  Tempranillo      92     30
secondEntry     NaN     Garnacha      89     25
2            France       Merlot      94     35
3            France   Chardonnay      91     40
4             Italy   Sangiovese      93     28

In [4]:
#both the row index and the column index have their own 'name' attribute. use rename_axis()
df.rename_axis("wines", axis='rows').rename_axis("fields", axis='columns')

fields country      variety  points  price
wines
0        Spain  Tempranillo      92     30
1          NaN     Garnacha      89     25
2       France       Merlot      94     35
3       France   Chardonnay      91     40
4        Italy   Sangiovese      93     28

# COMBINING

- concat(). given a list of elements, this function will smush those together along an axis.

- join(). lets you combine different DataFrame objects which have an index in common.

In [ ]:
#join two csv files in a single DataFrame

csv1 = pd.read_csv("xxxx.csv")
csv2 = pd.read_csv("xxxx.csv")

pd.concat([csv1, csv2])

In [ ]:
left = csv1.set_index(['title', 'trending_date'])
right = csv2.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_2', rsuffix='_1')