# HANDLING MISSING VALUES

In [2]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ana", "Ben", None, "David", "Eva", "Frank"],
    "Age": [24, np.nan, 31, 28, np.nan, 36],
    "City": ["Madrid", "Paris", "London", None, "Rome", "Berlin"],
    "Salary": [32000, 41000, np.nan, 39000, 45000, np.nan],
    "Active": [True, False, True, None, True, False],
}

df = pd.DataFrame(data)

print(df)

#both None and np.nan used for missing values
#in the 'Active' column, it is displayed as None bc it is boolean type, but still recognized as empty

    Name   Age    City   Salary Active
0    Ana  24.0  Madrid  32000.0   True
1    Ben   NaN   Paris  41000.0  False
2    NaN  31.0  London      NaN   True
3  David  28.0     NaN  39000.0   None
4    Eva   NaN    Rome  45000.0   True
5  Frank  36.0  Berlin      NaN  False

In [3]:
#num of missing values per column
missing_values_count = df.isnull().sum()

#display
missing_values_count[0:]

Name      1
Age       2
City      1
Salary    2
Active    1
dtype: int64

In [9]:
#percentage of data missing
total_cells = np.product(df.shape)
total_missing = missing_values_count.sum()
percentage_missing = (total_missing/total_cells) * 100

percentage_missing.round(2)

23.33

In [10]:
#remove rows with missing values
df.dropna()

  Name   Age    City   Salary Active
0  Ana  24.0  Madrid  32000.0   True

In [11]:
#remove all columns with missing values
cols_with_na = df.dropna(axis=1)
cols_with_na.head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [13]:
#replace all NA's with 0
filled_df = df.fillna(0)
filled_df

    Name   Age    City   Salary Active
0    Ana  24.0  Madrid  32000.0   True
1    Ben   0.0   Paris  41000.0  False
2      0  31.0  London      0.0   True
3  David  28.0       0  39000.0      0
4    Eva   0.0    Rome  45000.0   True
5  Frank  36.0  Berlin      0.0  False

In [17]:
#replace all NA's with whatever value comes directly after in the same column.
#then replace all the remaining na's with 0
filled_df = df.bfill(axis=0).fillna(0)
filled_df

    Name   Age    City   Salary Active
0    Ana  24.0  Madrid  32000.0   True
1    Ben  31.0   Paris  41000.0  False
2  David  31.0  London  39000.0   True
3  David  28.0    Rome  39000.0   True
4    Eva  36.0    Rome  45000.0   True
5  Frank  36.0  Berlin      0.0  False

# SCALING & NORMALIZATION